seamapi/react

.github/workflows/semantic-release.yml, src/lib/hooks/use-seam.ts
Re-enable the semantic release workflow
=> Enable semantic release

.storybook/main.ts, .storybook/preview.tsx, README.md, src/lib/components/DeviceManager/DeviceManager.stories.tsx
Updated Vercel config to set this env var.
=> Read publishableKey from env for storybook

README.md
@azat-co Thanks for catching this!
=> Pass prop in README docs

.github/workflows/chromatic.yml, .gitignore, README.md, package.json
Needs https://github.com/seamapi/react/pull/45
=> Publish to Chromatic

.storybook/preview.tsx, examples/basic/src/App.tsx, jest.config.cjs, test/fixtures/react.tsx, tsconfig.json
=> Use @seamapi/react over index.js as import path

src/lib/components/DeviceManager/DeviceManager.tsx
Just a quick fix to avoid the chromaic UI diff on each PR
=> Sort devices by id

package.json
See https://github.com/vitejs/vite/discussions/2657#discussioncomment-1345262
=> Add index.css to exports

src/lib/provider.tsx
See https://github.com/seamapi/react/discussions/72
Better to add it and remove it later if we can support it.
=> Add use client directive to provider

.storybook/main.ts, .storybook/preview-head.html, .storybook/webpack-csp.d.ts, .storybook/webpack-csp.js, README.md, vercel.json
Ensure we support and document how to use the components with CSP.
=> Strict CSP

src/lib/hooks/use-device.ts, src/lib/seam/use-seam-client.ts
- fix: Update query key for useDevice
- fix: Do not re-implement query cache
=> Fixes for query caching

src/lib/ui/Button.stories.tsx, src/lib/ui/Button.tsx, src/lib/ui/DeviceDetails/DeviceDetails.tsx, src/lib/ui/IconButton.tsx, src/styles/_access-code-table.scss, src/styles/_buttons.scss, src/styles/_colors.scss, src/styles/_device-details.scss, src/styles/_inputs.scss, src/styles/_main.scss, src/styles/_typography.scss
Partially addresses #110 by adding the `<Button/>` still need to hook it up to a mutation to make the call.
- Define all colors in **_colors.scss**
- Define all `$primary` color derivatives as outlined in figma
- Add button styles for all variants / sizes
=> Buttons & CSS Color Palette

src/lib/ui/AccessCodeDetails/AccessCodeDetails.tsx, src/lib/ui/AccessCodeTable/CodeDetails.tsx, src/lib/use-interval.ts, src/lib/use-is-date-in-past.ts
Otherwise the UI is not guaranteed to update.
=> Move logic dependent on current time to hook

.github/workflows/chromatic.yml, .storybook/preview.tsx, README.md, package-lock.json, package.json, src/lib/ui/AccessCodeDetails/AccessCodeDetails.stories.tsx, src/lib/ui/AccessCodeDetails/AccessCodeDetails.tsx, src/lib/ui/AccessCodeTable/AccessCodeTable.stories.tsx, src/lib/ui/AccessCodeTable/AccessCodeTable.tsx, src/lib/ui/DeviceDetails/DeviceDetails.stories.tsx, src/lib/ui/device/OnlineStatus.tsx
- Remove TODO
- Remove TODO note
- doc: Fix storybook comments
- Move publishableKey and userIdentifierKey to globalTypes
=> Hard-code IDs in storybook

.storybook/seed-fake.js
Requires https://github.com/seamapi/fake-seam-connect/pull/14, but should get the fake looking much closer to live
=> Device / Access Code - add more fake data

vercel.json
This is actually confirmed to be working via staging- the last merge was a silly mistake from not pushing a change.
=> csp image fix

README.md, package-lock.json, package.json, src/lib/ui/Alert/Alert.tsx, src/lib/ui/Alert/Alerts.tsx, src/lib/ui/Button.tsx, src/lib/ui/DeviceDetails/DeviceDetails.tsx, src/lib/ui/DeviceTable/DeviceHealthBar.tsx, src/lib/ui/Menu/Menu.tsx, src/lib/ui/SupportedDeviceTable/FilterCategoryMenu.tsx, src/lib/ui/SupportedDeviceTable/SupportedDeviceContent.tsx, src/lib/ui/SupportedDeviceTable/SupportedDeviceFilterArea.tsx, src/lib/ui/SupportedDeviceTable/SupportedDeviceRow.tsx, src/lib/ui/Table/TableFilterBar/TableFilterBar.tsx, src/lib/ui/TextField/TextField.tsx, src/styles/_main.scss, src/styles/_menus.scss, src/styles/_supported-device-table.scss
- fix: Use class over style for menu visibility
- fix: Rename seam-supported-devices-table class to match component
- fix: Use img width over style width
- refactor: Prefer PropsWithChildren
- refactor: Prefer && over ternary
- fix: Ensure optional bool props always default to false
- fix: Do not use defaultProps
- refactor: Simplify alertProps
=> Minor prop and name fixes

src/lib/ui/AccessCodeTable/AccessCodeTable.tsx, src/styles/_access-code-table.scss
=> feat(`AccessCodeTable`): add search

.storybook/seed-fake.js, package-lock.json, package.json
- feat: Update fake-seam-connect
- docs: Set created_at for storybook seed
=> Use fixed seed dates for storybook

api/fake-seam-connect.ts, api/fakepath.ts, src/lib/seam/components/AccessCodeDetails/AccessCodeDetails.tsx, src/lib/seam/components/AccessCodeDetails/AccessCodeDevice.tsx, src/lib/seam/components/AccessCodeTable/AccessCodeTable.tsx, src/lib/seam/components/AccessCodeTable/CodeDetails.tsx, src/lib/seam/components/DeviceDetails/DeviceDetails.tsx, src/lib/seam/components/DeviceTable/DeviceHealthBar.tsx, src/lib/seam/components/DeviceTable/DeviceTable.tsx, src/lib/seam/components/SupportedDeviceTable/FilterCategoryMenu.tsx, src/lib/seam/components/SupportedDeviceTable/SupportedDeviceContent.tsx, src/lib/seam/components/SupportedDeviceTable/SupportedDeviceFilterArea.tsx, src/lib/seam/components/SupportedDeviceTable/SupportedDeviceHeader.tsx, src/lib/seam/components/SupportedDeviceTable/SupportedDeviceRow.tsx, src/lib/seam/components/SupportedDeviceTable/SupportedDeviceTable.tsx, src/lib/seam/devices/use-toggle-lock.ts, src/lib/seam/use-seam-font.ts, src/lib/seam/use-seam-styles.ts, src/lib/ui/Menu/Menu.tsx, src/lib/ui/Menu/MenuItem.tsx, src/lib/ui/Menu/MoreActionsMenu.tsx, src/lib/ui/Table/TableFilterBar/TableFilterBar.tsx, src/lib/ui/Table/TableFilterBar/TableFilterItem.tsx, src/lib/ui/TextField/SearchTextField.tsx, src/lib/ui/clipboard.ts, src/lib/ui/use-interval.ts, vercel.json
- refactor: Fix types in fakepath
- refactor: Rename fake api target
- fix: Add missing return types
=> Add missing return types

package-lock.json, package.json
Need to update this first to enable the other PR that depends on this being on main.
=> docs: Update fake-seam-connect

README.md, package.json, src/stories/Introduction.mdx
- docs: Update README Description
- docs: Add native web components section
=> Document web components

src/lib/seam/components/DeviceTable/DeviceTable.stories.tsx, src/lib/seam/components/DeviceTable/DeviceTable.tsx, src/lib/seam/components/SupportedDeviceTable/SupportedDeviceTable.tsx
Should have already been like this.
=> fix: Allow components to take empty props

.gitignore, README.md, package-lock.json, package.json, src/elements.d.ts, src/elements.ts, src/lib/seam/use-seam-styles.ts, tsconfig.version.json, vite.config.ts
Needed for tools that use Webpack (like Angular). Closes https://github.com/seamapi/react/issues/211
- refactor: Build CSS to dist
- fix: Mark elements and css as having side effects
- refactor: Simplify prepack command
=> Mark files with side effects

src/lib/seam/components/DeviceTable/DeviceTable.element.ts, src/lib/seam/components/DeviceTable/DeviceTable.tsx
Could call this `onDeviceRowClick` however `Row` seems redundant here.
=> feat: Add onDeviceClick to DeviceTable

.github/workflows/_publish.yml, .github/workflows/publish.yml, .gitignore, .npmrc
- Revert "ci: Pass registry host on publish"
- fix: Remove .npmrc
=> Remove npmrc

package-lock.json, package.json, src/lib/seam/components/AccessCodeTable/AccessCodeTable.tsx, src/lib/seam/components/ConnectAccountButton/ConnectAccountButton.tsx, src/lib/seam/components/DeviceTable/DeviceTable.tsx, vite.config.ts
- Update seamapi
- feat: Do not pass accepted_providers when creating webview
- fix: Do not pass custom_redirect_failure_url
- Update eslint-config-standard-with-typescript
- Add missing return types
=> Update webview creation params

.github/workflows/chromatic.yml, .storybook/preview.tsx, README.md
Allows Chromaic to use the preview env for storybook! The `STORYBOOK_SEAM_ENDPOINT` var has been updated everywhere to always use the fake.
=> ci: Use vercel preview env on chromatic

package-lock.json, package.json, src/lib/seam/components/DeviceTable/DeviceHealthBar.stories.tsx, src/lib/seam/device-models/use-device-models.ts, src/lib/seam/index.ts
This hooks is unstable and should not have been exported.
=> fix: Do not export useDeviceModels hook

package-lock.json, package.json, src/lib/seam/components/DeviceTable/DeviceHealthBar.stories.tsx
Satisfies TS on the newSDK release
=> feat: Upgrade `seamapi` SDK and update error type property

src/lib/seam/components/DeviceTable/DeviceRow.tsx
Closes https://github.com/seamapi/react/issues/264
=> Show device offline if hub is disconnected

src/lib/seam/connect-webviews/use-create-connect-webview.ts
Noticed this was missing when reviewing the other PR.
=> feat: Export UseCreateConnectWebviewData type

.prettierrc.json, README.md, examples/basic/index.html, examples/index.html, examples/web-components/index.html, package-lock.json, package.json, src/styles/_menus.scss, src/styles/_supported-device-table.scss, src/styles/_typography.scss
- ci: Update to prettier v3
- build: Update to typescript v5.1
=> Update to prettier v3

package-lock.json, package.json, src/lib/seam/access-codes/use-create-access-code.ts, src/lib/seam/index.ts
- feat: Update seamapi to v7.1.0
- test: Update fake-seam-connect
- feat: Add useCreateAccessCode hook
=> feat: Add useCreateAccessCode hook

src/lib/seam/components/AccessCodeForm/AccessCodeFormTimezonePicker.tsx
Requested via [Slack]( https://hello-seam.slack.com/archives/C051ETBPRTQ/p1689874525095959?thread_ts=1689808685.428099&cid=C051ETBPRTQ)
https://github.com/seamapi/react/assets/11449462/0c3c7a1a-a515-4f83-8610-11f2cfe6ebf1
=> feat(AccessCodeForm): invert set time zone manually checkbox

src/lib/seam/components/AccessCodeForm/AccessCodeFormTimezonePicker.tsx
https://github.com/seamapi/react/assets/721372/304fc51d-4767-4e96-9722-a875d62323ec
=> Do not disable timezone select

src/lib/seam/components/AccessCodeTable/AccessCodeTable.tsx, src/lib/seam/components/DeviceTable/DeviceTable.tsx
Closes #308 • Adds a `title` prop to table components with a top-level title.
=> feat: Add `title` prop for table components

src/lib/ui/device/BatteryStatus.tsx
Customer request:
https://hello-seam.slack.com/archives/C04SGND5QL9/p1690220694132189?thread_ts=1690220662.657769&cid=C04SGND5QL9
src="https://github.com/seamapi/react/assets/11382084/ccfe024e-a16e-4f44-86c9-3813da6ea64e">
=> feat: Add battery percentage to `BatteryStatus`

package-lock.json, package.json
Bumps SDK version • Pulls the new thermostat models
=> feat: Bump SDK

package-lock.json, package.json
Includes auth header update from sdk which should resolve caching issues.
=> feat: Update to seamapi v8.2.4

src/lib/seam/components/AccessCodeDetails/AccessCodeDetails.tsx
Was supposed to be this value. This component is not released yet.
=> fix: Edit access code should be disabled

package-lock.json, package.json, src/lib/element.tsx, src/lib/seam/components/DeviceTable/DeviceTable.element.ts, src/lib/seam/components/SupportedDeviceTable/SupportedDeviceTable.element.ts
- feat: Accept csv or json for web component array attributes
See https://github.com/rxfork/react-to-web-component/pull/3
=> feat: Accept csv or json for web component array attributes

.github/workflows/format.yml, README.md, terraform/.gitignore, terraform/.terraform.lock.hcl, terraform/main.tf, terraform/provider.tf, terraform/variables.tf, terraform/versions.tf
Create a Cloudfront R2 bucket to serve the assets. Need to create the bucket first, then publish via action in another PR.
=> Add R2 bucket

.github/workflows/check.yml, .github/workflows/publish.yml, README.md, terraform/main.tf
Confirmed working https://github.com/seamapi/react/actions/runs/5767704823/job/15637818146
=> Publish assets to R2

.github/workflows/check.yml, .github/workflows/publish.yml
Slight mistake in this commit https://github.com/seamapi/react/pull/338/commits/2bacb55575dc5111432b618e3c3619ede2daed73
=> fix: Publish assets for version

.github/workflows/publish.yml
Need to remove the v from v.1.2.3 etc
=> fix: Remove v from bucket version path

src/lib/ui/Tooltip/Tooltip.stories.tsx, src/lib/ui/Tooltip/Tooltip.tsx
=> Address `Tooltip` PR changes

.eslintrc.json, src/lib/seam/components/AccessCodeDetails/AccessCodeDetails.stories.tsx, src/lib/seam/components/AccessCodeTable/AccessCodeHealthBar.stories.tsx, src/lib/seam/components/AccessCodeTable/AccessCodeTable.stories.tsx, src/lib/seam/components/ClimateSettingScheduleTable/ClimateSettingScheduleTable.stories.tsx, src/lib/seam/components/CreateAccessCodeForm/CreateAccessCodeForm.stories.tsx, src/lib/seam/components/DeviceDetails/DeviceDetails.stories.tsx, src/lib/seam/components/DeviceTable/DeviceHealthBar.stories.tsx, src/lib/seam/components/EditAccessCodeForm/EditAccessCodeForm.stories.tsx, src/lib/seam/components/SupportedDeviceTable/SupportedDevice.stories.tsx, src/lib/ui/Tooltip/Tooltip.tsx
- refactor: Remove hook dependency warnings
- ci: Make react-hooks/exhaustive-deps an error
- ci: Disable react-hooks/rules-of-hooks in stories
=> Resolve linter warnings

package-lock.json, package.json, src/lib/seam/access-codes/use-generate-access-code-code.ts
- Update seamapi and fake-seam-connect
- Add useGenerateAccessCodeCode
=> Add useGenerateAccessCodeCode

.github/workflows/chromatic.yml, src/lib/element.tsx, src/lib/seam/SeamProvider.tsx
It probably should have been defined like this to start.
=> fix: Extend SeamProviderBaseProps from PropsWithChildren

.github/workflows/semantic-release.yml
=> Update semantic-release-action to v4

src/lib/ui/thermostat/ClimateSettingStatus.stories.tsx, src/lib/ui/thermostat/ClimateSettingStatus.tsx, src/lib/ui/thermostat/Temperature.stories.tsx, src/lib/ui/thermostat/Temperature.tsx
Simple temperature display to reduce repetitive logic across related components
=> Add `Temperature` component

src/lib/ui/thermostat/Temperature.tsx
Ref: https://github.com/seamapi/react/pull/353#issuecomment-1702994312
=> Make all temperatures integers

src/lib/seam/components/ClimateSettingScheduleDetails/ClimateSettingScheduleCard.tsx, src/lib/seam/components/ClimateSettingScheduleDetails/ClimateSettingScheduleDetails.tsx, src/lib/seam/components/ClimateSettingScheduleDetails/ClimateSettingScheduleDeviceBar.tsx
I think tristan's still working on device details for thermostats, just wanted this here so we're ready for it.
=> CS Schedule should link to the corresponding device  

package-lock.json, package.json, src/lib/seam/components/DeviceDetails/ThermostatDeviceDetails.tsx
- Also, we should probably display the default climate setting here, not the current one
=> fix: Show default climate setting in correct section

src/lib/ui/thermostat/TemperatureControl.tsx
Modifies the value propagation logic in the `TemperatureControl` component to support arbitrary restrictions imposed on `value` directly.
=> Fix `TemperatureControl` value logic

src/lib/seam/components/SupportedDeviceTable/SupportedDeviceRow.tsx, src/styles/_supported-device-table.scss
=> Display LIVE/CONTACT SUPPORT for Lockly

src/lib/ui/AccessCodeForm/AccessCodeFormTimezonePicker.tsx, src/lib/ui/TimezonePicker/TimezonePicker.stories.tsx, src/lib/ui/TimezonePicker/TimezonePicker.tsx, src/styles/_access-code-form.scss, src/styles/_main.scss, src/styles/_timezone-picker.scss
I wanted this broken out so I can re-use it for creating climate setting schedules
=> TimezonePicker UI Component

src/lib/telemetry/client.ts, src/lib/telemetry/hooks.ts
- Add group spec
- Add page spec
- Send telemetry.group
=> feat: Send group telemetry

package-lock.json, package.json
=> feat: Update seamapi to v8.13.0

src/lib/seam/components/SupportedDeviceTable/SupportedDeviceRow.tsx, src/styles/_supported-device-table.scss
This reverts commit 78748d9b890c7fd6bd320cd8b8d41e77db566139.
=> Revert "Display LIVE/CONTACT SUPPORT for Lockly (#459)"

src/lib/seam/components/SupportedDeviceTable/SupportedDeviceFilterResultRow.tsx, src/lib/seam/components/SupportedDeviceTable/SupportedDeviceRow.tsx, src/styles/_supported-device-table.scss
fixes #427 
https://github.com/seamapi/react/assets/11449462/bbbc610e-62af-4e94-ab23-2905c2bbf4fb
https://github.com/seamapi/react/assets/11449462/245daea9-f228-4fcb-a7fe-26d9e7db9b48
=> fix(SupportedDeviceTable): model name/number wrapping

README.md, src/lib/seam/SeamProvider.tsx, src/lib/seam/components/AccessCodeDetails/AccessCodeDetails.stories.tsx, src/lib/seam/components/AccessCodeTable/AccessCodeTable.stories.tsx, src/lib/seam/components/ClimateSettingScheduleDetails/ClimateSettingScheduleDetails.stories.tsx, src/lib/seam/components/ClimateSettingScheduleTable/ClimateSettingScheduleTable.stories.tsx, src/lib/seam/components/CreateAccessCodeForm/CreateAccessCodeForm.stories.tsx, src/lib/seam/components/CreateClimateSettingScheduleForm/CreateClimateSettingScheduleForm.stories.tsx, src/lib/seam/components/DeviceDetails/DeviceDetails.stories.tsx, src/lib/seam/components/DeviceTable/DeviceTable.stories.tsx, src/lib/seam/components/EditAccessCodeForm/EditAccessCodeForm.stories.tsx, src/lib/seam/components/SupportedDeviceTable/SupportedDevice.stories.tsx, src/lib/ui/Menu/Menu.tsx
- feat: Export seamComponentsClassName
- docs: Document how to use inside modal dialog
- docs: Always use seamComponentsClassName export
=> Document use in modal dialog

src/lib/ui/AccessCodeForm/AccessCodeForm.tsx, src/lib/ui/Button.tsx, src/styles/_access-code-form.scss
closes #436
- Uses `react-hook-form` for validation
https://github.com/seamapi/react/assets/11449462/9c4c525a-36af-4ac8-a413-75c769ec57d1
=> fix(AccessCodeForm): add code length validation

vite.config.ts
Regression introduces when adding vitest.
=> fix: Element bundle has null version and non-production React mode

src/lib/ui/LoadingToast/LoadingToast.stories.tsx, src/lib/ui/LoadingToast/LoadingToast.tsx
Totally forgot to add this in before
=> Add `label` to `LoadingToast`

src/lib/ui/Snackbar/Snackbar.tsx
Hard to see both in code and in the component lol
=> Remove straggling `S` in `Snackbar`

.storybook/seed-fake.js
Fix description for `failed_to_set_on_device`
=> test: Fix description for `failed_to_set_on_device`

src/lib/seam/components/AccessCodeTable/AccessCodeTable.tsx, src/lib/seam/components/CreateAccessCodeForm/CreateAccessCodeForm.element.ts, src/lib/seam/components/CreateAccessCodeForm/CreateAccessCodeForm.tsx, src/lib/seam/components/EditAccessCodeForm/EditAccessCodeForm.element.ts, src/lib/seam/components/EditAccessCodeForm/EditAccessCodeForm.tsx, src/lib/ui/Snackbar/Snackbar.tsx, src/styles/_snackbar.scss
closes #479 
supersedes #515 
- Adds `onSuccess` prop as discussed in https://github.com/seamapi/react/pull/515#issuecomment-1749239497
- Remove local `hidden` state in `<Snackbar/>`. This avoids having to conditionally render the snackbar, and any potential issues with multiple states (parent, and local).
- Flipped snackbar to display hidden by default, and only show/animate when visible. 
https://github.com/seamapi/react/assets/11449462/aa516064-329f-47a3-b768-1ae5a89c8781
=> feat(AccessCodeForm): Show confirmation message after creating or updating an access code

README.md, package-lock.json, package.json, src/lib/element.tsx, src/lib/seam/SeamProvider.tsx
- Update all dependencies
- feat: Add onInit to SeamProvider
=> feat: Add onSessionUpdate prop to get client instance

.storybook/preview.tsx, .storybook/seed-fake.js, package-lock.json, package.json, src/lib/seam/components/DeviceDetails/DeviceDetails.test.tsx, src/lib/seam/components/DeviceTable/DeviceTable.test.tsx, test/fixtures/api.ts, test/fixtures/react.tsx, test/fixtures/seed-fake.ts, test/main.test.tsx, tsconfig.json
Just need to get some dependency updates in for other work and prefer to isolate them to a separate PR.
=> Update fake-seam-connect and fix seed data

README.md, src/lib/seam/components/SupportedDeviceTable/SupportedDeviceTableManufacturerKeys.stories.tsx, vercel.json
Images should all be coming thought one domain now.
=> docs: Remove seam.co from CSP

src/lib/seam/access-codes/use-access-codes.ts, src/lib/seam/components/SupportedDeviceTable/use-device-models.ts, src/lib/seam/components/SupportedDeviceTable/use-manufacturers.ts, src/lib/seam/devices/use-devices.ts, src/lib/seam/thermostats/climate-setting-schedules/use-climate-setting-schedules.ts
- Remove comments
- fix: Prime manufacturer cache
- fix: Prime cache for device models
- fix: Prime cache for access codes
=> Prime cache for queries

src/lib/seam/thermostats/use-update-fan-mode.ts, src/lib/seam/thermostats/use-update-thermostat.ts
Fixes the query key for thermostat mutation hooks.
=> Correct query key for thermo mutation hooks

src/lib/seam/components/AccessCodeTable/AccessCodeMainIcon.tsx, src/lib/seam/components/AccessCodeTable/AccessCodeRow.tsx, src/lib/seam/components/AccessCodeTable/CodeDetails.tsx, src/styles/_main.scss, src/styles/_seam-table.scss, src/styles/_visibility.scss
closes #450
Fixed according to spec in https://www.figma.com/file/Su3VO6yupz4yxe88fv0Uqa/Seam-Components?type=design&node-id=2384-111787&mode=design&t=GiCQZtP2y2MoA6iS-0 - amazing how much better it is.
https://github.com/seamapi/react/assets/11449462/bc3211dd-5a2e-4516-b34f-a6b9bfa76975
=> fix(AccessCodeTable): layout broken on mobile

src/lib/seam/components/SupportedDeviceTable/SupportedDeviceContent.tsx, src/lib/seam/components/SupportedDeviceTable/SupportedDeviceTable.element.ts, src/lib/seam/components/SupportedDeviceTable/SupportedDeviceTable.stories.tsx, src/lib/seam/components/SupportedDeviceTable/SupportedDeviceTable.tsx, src/lib/seam/components/SupportedDeviceTable/use-filtered-device-models.ts
- feat(SupportedDeviceTable): Add excludeIf and includeIf props
=> feat(SupportedDeviceTable): Add excludeIf and includeIf props

README.md
This should be updated automatically, but it got stuck. Will check if it's working on next version.
=> docs: Update CSS version in README

src/lib/seam/SeamProvider.tsx
The provider previously threw if you attempted to pass a client. Happy to add a test with some guidance, not entirely sure how to.
=> fix: Error when passing a Seam client to the SeamProvider

.github/workflows/format.yml, terraform/versions.tf
- Update terraform to v1.7
- Add terraform fmt to generate workflow
=> Update Terraform version

package-lock.json, package.json, src/lib/seam/access-codes/use-access-codes.ts, src/lib/seam/access-codes/use-create-access-code.ts, src/lib/seam/access-codes/use-delete-access-code.ts, src/lib/seam/access-codes/use-generate-access-code-code.ts, src/lib/seam/components/AccessCodeDetails/AccessCodeDetails.tsx, src/lib/seam/components/AccessCodeTable/AccessCodeMenu.tsx, src/lib/seam/components/ConnectAccountButton/ConnectAccountButton.tsx, src/lib/seam/components/CreateAccessCodeForm/CreateAccessCodeForm.tsx, src/lib/seam/components/CreateClimateSettingScheduleForm/CreateClimateSettingScheduleForm.tsx, src/lib/seam/components/EditAccessCodeForm/EditAccessCodeForm.tsx, src/lib/seam/components/SupportedDeviceTable/use-device-models.ts, src/lib/seam/components/SupportedDeviceTable/use-manufacturers.ts, src/lib/seam/devices/use-devices.ts, src/lib/seam/thermostats/climate-setting-schedules/use-climate-setting-schedules.ts, src/lib/seam/thermostats/climate-setting-schedules/use-create-climate-setting-schedule.ts, src/lib/seam/thermostats/climate-setting-schedules/use-delete-climate-setting-schedule.ts, src/lib/ui/AccessCodeForm/AccessCodeForm.tsx
This does change the signature of some of our hooks (`isLoading` -> `isPending`), but I'm not sure whether we consider the hooks part of our public API? cc @razor-x
=> Upgrade react-query to v5

src/lib/seam/components/ClimateSettingScheduleDetails/ClimateSettingScheduleDetails.tsx, src/lib/seam/thermostats/climate-setting-schedules/use-update-climate-setting-schedule.ts
closes #395 
- Also adds `useUpdateClimateSettingSchedule`
=> feat(Thermostats): add manual override toggle for ClimateScheduleDetails

.storybook/devicedb-seed.json, src/lib/seam/components/SupportedDeviceTable/SupportedDeviceTable.stories.tsx
- **docs: Update devicedb seed**
- **docs: Add note about sample data**
=> docs: Update Storybook device model data

.storybook/seed-fake.js, src/lib/seam/components/DeviceDetails/NoiseSensorDeviceDetails.tsx, src/lib/seam/components/DeviceTable/DeviceTable.tsx
- Adds noise sensors to `DeviceTable`
- Adds `ContentHeader` to `NoiseSensorDeviceDetails`
- Adds `properties.image_url` to fix fallback for seed device
=> feat: Add Noise Sensors to `DeviceTable`

.storybook/seed-fake.js, package-lock.json, package.json, src/lib/seam/components/DeviceDetails/NoiseSensorDeviceDetails.tsx, src/lib/ui/device/NoiseLevelStatus.tsx
=> feat: Add noise level to `NoiseSensorDeviceDetails`

src/lib/seam/components/DeviceDetails/LockDeviceDetails.tsx, src/lib/seam/components/DeviceDetails/NoiseSensorDeviceDetails.tsx, src/lib/ui/device/EditableDeviceName.tsx, src/lib/ui/thermostat/ThermostatCard.tsx
Only public components should be under lib/seam.
- **Rename SeamEditableDeviceName to EditableDeviceName**
- **Move private functions down**
=> Rename SeamEditableDeviceName to EditableDeviceName

package-lock.json, package.json
- **Update to @seamapi/types v1.344.1**
- **Update to @seamapi/http v1.20.0**
=> feat: Update to @seamapi/http@v1.20.0
