README.md, examples/basic/src/App.tsx
- docs: Link to Storybook in README
- docs: Add example code to README
- Wrap entire example app in SeamProvider
- docs: Update development section in README
=> Usage and dev docs in README

.storybook/preview.tsx, examples/basic/index.html, examples/basic/vite.config.js, package-lock.json, package.json, vercel.json
Will use the real Seam endpoint (no proxy) on deployment. I suspect we will still want the local dev proxy, but can test that after this is confirmed working.
=> Use SEAM_ENDPOINT if defined in docs

.devcontainer/devcontainer.json
Webpack hungry. Feed webpack more ram!
=> Set 8gb devcontainer requirement

src/lib/icons/Seam.tsx, svgr.config.cjs
Currenly returning `ReactNode` which isn't a valid react element for function components. This PR updates the return type to `JSX.Element`
TS error:
Reference: https://stackoverflow.com/questions/58123398/when-to-use-jsx-element-vs-reactnode-vs-reactelement/72353143#72353143
=> SVG - update generate to return JSX.Element

package-lock.json, package.json, src/lib/ui/DeviceDetails/DeviceDetails.tsx, src/styles/_device-details.scss, src/styles/_main.scss, src/styles/_reset.scss
Fixes #88
Fixes #82
Was due to the missing CSS reset.
- removed `the-new-css-reset`
- Added custom `./reset.scss` crediting [source](https://www.boag.online/blog/css-reset)
- Added 'Device' label above the name
=> Device Details - Fix incorrect spacing and missing CSS reset

src/lib/ui/AccessCodeTable/AccessCodeTable.stories.tsx, src/lib/ui/AccessCodeTable/AccessCodeTableContent.tsx, src/styles/_layout.scss
Fixes #93 
Was due to `width: 100%` on the header component. Good to remove as any layout should use `flex` to avoid width issues because we're not sure what the parent component would be.
After #80 was merged, we lost the ability to preview `AccessCodeTable` in storybook because without a fake it was trying to make real api calls.
As a temporary workaround, I've refactored out `AccessCodeTableContent` which is the UI for `AccessCodeTable`, without the data-binding. I've also updated the story to use `AccessCodeTableContent` for now until the fake client is ready.
=> Fix access code table layout

src/lib/seam/access-codes/use-access-codes.ts, src/lib/seam/devices/use-device.ts, src/lib/seam/devices/use-devices.ts, src/lib/seam/devices/use-toggle-lock.ts, src/lib/ui/AccessCodeDetails/AccessCodeDetails.tsx, src/lib/ui/AccessCodeDetails/AccessCodeDevice.tsx, src/lib/ui/Button.tsx, src/lib/ui/DeviceDetails/DeviceDetails.stories.tsx, src/lib/ui/DeviceDetails/DeviceDetails.tsx, src/lib/ui/DeviceTable/DeviceTable.tsx
Closes #110 
- Optimistic UI updates via `onMutate` for snappy UI.
- Set query data manually on `device.list` to pre-populate `device.get`.
- Pass `deviceId` to `<DeviceDetails/>` to avoid maintaining duplicate state.
- Removed `useFakeDevice` (no longer required).
- Need to update both the `/lock_door`, and `/unlock_door` endpoints on `seam-connect` with client session token auth.
=> Device - Add lock/unlock

.storybook/middleware.js, .storybook/preview.tsx, .storybook/seed-fake.js, README.md, examples/.env.storybook, examples/vite.config.ts, package-lock.json, package.json, test/fixtures/react.tsx, test/jest/global-setup.cjs
Makes the fake an opt-out experience. The production storybook now uses the read-only fake.
The only reason to support the real api at this point for the storybook is because the fake is read only so action attempts can't be polled, webviews can't be finished etc.
We'll have a fake setup that supports modifications soon that will support mutating, so it's a temporary limitation for some of the interactive storybooks.
Making sure everyone develops the same reproducible way is the goal. Some things in the demo don't look right as a result of this- those are bugs that should be fixed. It's more important to have our development environment reflect those bugs then to continue testing against live and having "it works on my system" issues.
=> Always use the fake (unless very explicitly opted out)

.stylelintrc.json
Disables the Stylelint `no-descending-specificity` rule because:
1. Stylelint cannot access our HTML code and therefore can only interpret usage from our CSS; and
2. This rule is more applicable to the old ways of writing CSS where selectors and descending specificity was more or less the way to go. Considering that we use SCSS and that we have much better and more modern methods of selecting elements, this rule is, in my opinion, a big time waster when trying to make the linter happy. This rule is outdated.
In my PRs on this project, I've spent more time than I should trying to make the linter happy by moving around blocks of code that I know will work. Moreover, you often find yourself in a situation where moving one block above another, as the linter suggests, just causes it to throw …
=> fix: Disable `no-descending-specificity` lint rule

src/lib/ui/AccessCodeTable/CodeDetails.tsx
Everything was Unit 110, everywhere.
=> fix(`AccessCodeTable`): device name was always hardcoded as Unit 110

.storybook/preview.tsx, README.md, examples/basic/index.html, examples/basic/src/App.tsx, src/lib/SeamProvider.tsx, src/lib/seam/use-seam-font.ts, src/lib/seam/use-seam-styles.ts, test/fixtures/react.tsx
Simplifies API examples because you don't need to import CSS or a font
https://hello-seam.slack.com/archives/C051ETBPRTQ/p1685131057245149
=> feat: Automatic style loading

.storybook/preview.tsx, README.md, vercel.json
- Allows us to provide a stable URL for assets independent of the backing CDN.
- Font's still need to come from Google Fonts as re-hosting that is non-trivial (also not versioned, so no need to rehost).
- Once this is on main, can update the internal URL and fix the version replacement at build time.
=> docs: Proxy unpkg

examples/basic/src/App.tsx, examples/basic/src/main.tsx, package.json, src/lib/SeamProvider.tsx, src/lib/seam/use-seam-font.ts, src/lib/seam/use-seam-styles.ts, src/lib/version.ts
- refactor: Prefer disabled over enabled
- refactor: Return early from effect
- docs: Import CSS in example
- feat: Add useUnminifiedCss prop
- fix: Use correct version for stylesheet
=> Use correct CSS version when injecting link tag

src/lib/seam/SeamProvider.tsx, src/lib/seam/components/SupportedDeviceTable/FilterCategoryMenu.tsx
Splitting this out to test separately and simplify the web components PR. 
- fix: Remove use client directive
- fix: Add check for valid provider options
- refactor: Move injection hooks up
- refactor: Match unminifiedCss prop name
- feat: Add queryClient prop to SeamProvider
- fix: Update context if provider props change
- feat: Export SeamProviderProps and interfaces
- refactor: Prefer to extend base props
- fix: Do not throw in createSeamContextValue
=> Required updates for web components

README.md, examples/basic/src/App.tsx, examples/web-components/index.html, src/lib/seam/components/ConnectAccountButton/ConnectAccountButton.element.ts, src/lib/seam/components/ConnectAccountButton/ConnectAccountButton.stories.tsx, src/lib/seam/components/ConnectAccountButton/ConnectAccountButton.tsx, src/lib/seam/components/elements.ts, src/lib/seam/components/index.ts, src/lib/seam/connect-webviews/use-create-connect-webview.ts, src/lib/seam/devices/use-toggle-lock.ts, src/lib/seam/index.ts
This is the missing button to make all of the publishable key examples work without needing to setup the the client session first with a separate backend call.
- feat: Add useCreateConnectWebview
- feat: Add ConnectAccountButton
- Document ConnectAccountButton
- Add seam-connect-account-button
=> Connect account button

.github/workflows/check.yml, .github/workflows/chromatic.yml, .github/workflows/format.yml, .github/workflows/generate.yml, README.md
- ci: Adjust workflow triggers for contributors
- Needed so workflows with secrets do not run and fail on forks. ref: https://github.com/seamapi/ruby/pull/51
- Allow chromatic to run on forks
- See https://www.chromatic.com/docs/custom-ci-provider#run-chromatic-on-external-forks-of-open-source-projects
=> OSS friendly workflow triggers

src/lib/ui/Alert/Alert.tsx, src/styles/_alert.scss
Updates the styling of the `Alert` component to match the updated design spec (not sure when it changed). This will be used in #243.
---
=> fix: Update `Alert` style to match design spec

src/lib/seam/components/SupportedDeviceTable/SupportedDevice.stories.tsx, src/lib/seam/components/SupportedDeviceTable/SupportedDeviceTable.element.ts, src/lib/seam/components/SupportedDeviceTable/SupportedDeviceTable.tsx
Prop convention is moving to `disable/enable` prefixes, see e.g., https://github.com/seamapi/react/issues/238
=> feat: Add disableFilter and deprecate cannotFilter

README.md
This should have been done eariler so the preview env always uses the fake api on the preview env not main.
=> ci: Do not set STORYBOOK_SEAM_ENDPOINT on vercel

src/lib/seam/SeamProvider.tsx, src/lib/ui/Alert/Alerts.tsx, src/lib/ui/Button.tsx, src/lib/ui/Menu/Menu.tsx, src/lib/ui/Menu/MenuItem.tsx, src/lib/ui/Menu/MoreActionsMenu.tsx
- fix: SeamProviderProps now includes children
- refactor: Always extend PropsWithChildren
Props to @mikewuu for figuring this one out: https://github.com/seamapi/react/pull/271#discussion_r1260448184
=> Always extend from PropsWithChildren

src/lib/seam/components/DeviceTable/DeviceTable.test.tsx, src/lib/seam/use-seam-client.ts, test/fixtures/react.tsx
- test: Create QueryClient for each test
- fix: Disallow using apiKey with client
Tests were passing but not really testing what we wanted before:
- Locally: I have SEAM_API key set in my environment. This is the only env var used by the Seam SDK. This was causing the client to fail to initialize as API key and publishable key are incompatible.
- On CI: Tests might have worked, but the test only tested for the loading state, which always happens, so the test passed as soon as it saw the loading state.
- Now: The `apiKey` is passed in explicitly as `undefined`. Current logic in the SDK will respect that as it only sets properties that are not explicitly passed in.
This means testing with https://testing-library.com/ is now fully working.  Further discussion on what to use tests for can be …
=> Test DeviceTable loads data

README.md, package.json, preversion.ts, tsconfig.json, version.ts
We could move the scripts to a sub directory, but I don't mind them at the top level right now. I reserve the right change my mind about that 🙃
This unlocks the ability to have more examples that stay up to date / examples outside the README. It's not clear how to keep the external docs updated with the latest version, but that's out of scope of this repo anyway.
=> build: Keep README version up to date

src/lib/seam/components/AccessCodeTable/AccessCodeTable.element.ts, src/lib/seam/components/AccessCodeTable/AccessCodeTable.tsx, src/lib/seam/components/DeviceTable/DeviceTable.element.ts, src/lib/seam/components/DeviceTable/DeviceTable.tsx
Deprecates the `title` prop for `DeviceTable`, `AccessCodeTable`—adds `heading` as a replacement.
=> feat: Add `heading` prop, deprecate `title`

src/lib/seam/access-codes/use-delete-access-code.ts, src/lib/seam/components/AccessCodeDetails/AccessCodeDetails.element.ts, src/lib/seam/components/AccessCodeDetails/AccessCodeDetails.tsx, src/lib/seam/components/AccessCodeTable/AccessCodeMenu.tsx, src/lib/seam/components/AccessCodeTable/AccessCodeRow.tsx, src/lib/seam/components/AccessCodeTable/AccessCodeTable.element.ts, src/lib/seam/components/AccessCodeTable/AccessCodeTable.tsx, src/lib/ui/Menu/MenuItem.tsx, src/styles/_access-code-details.scss, src/styles/_access-code-table.scss
Closes #327 
- https://github.com/seamapi/fake-seam-connect/pull/48
- Added a `disableDeleteAccessCode` prop, similar to `disableEditAccessCode`.
- Added **View code details menu item**
https://github.com/seamapi/react/assets/11449462/7dc34ac8-99ab-4b94-b696-ef9578d7eace
=> feat(AccessCode): add ability to delete

src/lib/seam/components/SupportedDeviceTable/SupportedDeviceFilterArea.tsx, src/lib/seam/components/SupportedDeviceTable/use-filtered-device-models.ts
- When brands is null, the excluded brand filter was not applied before.
=> fix(SupportedDeviceTable): excludedBrands prop would not filter

src/lib/seam/components/SupportedDeviceTable/SupportedDeviceContent.tsx
This was generating a warning in the console. I think it was left over from an older table based design?
=> fix: Use div over td

terraform/main.tf, terraform/outputs.tf, vercel.json
- Use R2 DNS type
- Use output for custom R2 domain
- feat: Serve assets from R2
See https://react.seam.net/v/1.45.2/dist/elements.js and via preview env https://react-git-serve-assets-from-bucket-seamapi.vercel.app/v/1.45.2/dist/elements.js
=> Serve assets from R2

vercel.json
Needed to allow js files to be loaded via script tag. Verified working via
=> fix: Set CORS headers for assets

src/lib/ui/thermostat/ClimateSettingStatus.tsx
Toggle between fahrenheit and celsius reference depending on `temperatureUnit`
=> Fix `ClimateSettingStatus` temperature unit

src/lib/element.tsx, src/lib/seam/use-seam-client.ts, src/lib/ui/Menu/Menu.tsx, src/lib/ui/clipboard.ts
This was inconsistent. I think we can just assume `globalThis` is defined vs the other way of putting the `?.` everywhere.
=> refactor: Prefer globalThis. over globalThis?.

.stylelintrc.json
Disables the `scss/operator-no-newline-after` stylelint rule since this will conflict with the formatter for longer lines (which aren't very common in SCSS except for, usually, math ops).
=> Disable `operator-no-newline-after` in Stylelint

src/styles/_tooltip.scss
Minor fix to the layout of the tooltip button icon—was a bit off when used in ref to other components
=> Fix `Tooltip` icon layout

src/styles/_layout.scss
It looks like the browser had some of its own styles for buttons, so it was necessary to add this css rule here.
=> Fixed font for `AccordionRow`

src/lib/ui/layout/DetailSection.tsx, src/lib/ui/layout/DetailSectionGroup.stories.tsx
`ClimateSettingScheduleDetails` has sections without labels
=> Make `label` optional for `DetailSection`

src/lib/seam/components/AccessCodeDetails/AccessCodeDetails.stories.tsx, src/lib/seam/components/AccessCodeTable/AccessCodeTable.stories.tsx, src/lib/seam/components/ClimateSettingScheduleDetails/ClimateSettingScheduleDetails.stories.tsx, src/lib/seam/components/ClimateSettingScheduleTable/ClimateSettingScheduleTable.stories.tsx, src/lib/seam/components/ConnectAccountButton/ConnectAccountButton.stories.tsx, src/lib/seam/components/CreateAccessCodeForm/CreateAccessCodeForm.stories.tsx, src/lib/seam/components/DeviceDetails/DeviceDetails.stories.tsx, src/lib/seam/components/DeviceTable/DeviceTable.stories.tsx, src/lib/seam/components/EditAccessCodeForm/EditAccessCodeForm.stories.tsx, src/lib/seam/components/SupportedDeviceTable/SupportedDevice.stories.tsx
This will require find/replace on the api-docs repo, but long term I think it makes more sense. Holding off on merge until next week.
See https://github.com/seamapi/api-docs/pull/177
=> Rename story section from Example to Components

assets/icons/chevron-down.svg, src/lib/icons/ChevronDown.tsx
Same issue as #443 • Different browsers have different policies about this, it seems.
=> Fix `ChevronDownIcon` mask ref

src/lib/seam/components/EditAccessCodeForm/EditAccessCodeForm.element.ts
The same name was used for both CreateAccessCodeForm and EditAccessCodeForm, causing this error when trying to use native web components:
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "seam-access-code-details" has already been used with this registry
at yO (https://react.seam.co/v/1.55.0/dist/elements.js:8251:48)
at https://react.seam.co/v/1.55.0/dist/elements.js:28109:15
=> fix: Custom element name conflict with CreateAccessCodeForm 

src/lib/ui/Menu/Menu.tsx
fixes #424 
Messed with iframe calculations a bunch, but the fix was much simpler, just use `offsetTop` instead of `getBoundingClientRect`
https://github.com/seamapi/react/assets/11449462/693b0782-670e-41f4-b677-b8d8547a3876
=> fix(Menu/Dropdown): incorrect position in storybook/docs

src/styles/_supported-device-table.scss
=> fix(SupportedDeviceTable): set white bg to always match fade white overlay

src/lib/icons/ChevronDown.tsx, src/lib/seam/components/SupportedDeviceTable/FilterCategoryMenu.tsx, src/lib/ui/Menu/Menu.tsx, src/styles/_supported-device-table.scss
Closes #425 
See [commits](https://github.com/seamapi/react/pull/503/commits) for list of changes.
- Now calculating container dimensions via `body` which doesn't change depending on content.
https://github.com/seamapi/react/assets/11449462/bce78d7b-9f65-4875-a240-f87c45d436e7
- **Filter** button is showing again.
- Opening nested menu will align to correct anchor.
- Multiple menus in storybook still open / are positioned correctly.
- Menus only open up if there is enough space. No clipping.
- Opening a menu after scrolling (and while scrolling) still positions the menu correctly.
=> Menu fixes

.storybook/preview.tsx, .storybook/seed-fake.js, package-lock.json, package.json, src/lib/seam/components/DeviceTable/DeviceTable.stories.tsx, test/fixtures/seed-fake.ts
Adds the ability to simulate outages by toggling between publishable keys.
---
Note: Going from `Normal` to `Outage` sometimes requires a reload. Any ideas on how we can eliminate this?
=> test: Simulate outages

src/lib/seam/components/DeviceDetails/ThermostatDeviceDetails.tsx
The design does not have a tooltip for device details
=> fix: Remove tooltip device details in `ThermostatDeviceDetails`

src/lib/seam/access-codes/use-update-access-code.ts, src/lib/seam/components/EditAccessCodeForm/EditAccessCodeForm.tsx
closes #491
We were previously re-fetching the AccessCode immediately after a successful update response. This would occasionally happen before the Action Attempt has been processed, resulting in stale data back.
The fix here is to just optimistically update the UI, and assume the action will eventually be successful. 
If the user refreshes, and the action hasn't been processed, they would still see the old (stale) data. Although this isn't ideal, it's still better than the current situation, which doesn't provide any feedback that the data has changed at all.
- Also fixed a bug where updating an `ongoing` Access Code's code wouldn't have worked.
https://github.com/seamapi/react/assets/11449462/23191a80-9eec-4ab1-9915-2dce1013822f …
=> fix(AccessCode): stale data after update

.storybook/devicedb-seed.json, .storybook/middleware.js, .storybook/update-devicedb-seed.ts, package-lock.json, package.json, src/lib/seam/components/SupportedDeviceTable/use-device-model.ts, src/lib/seam/components/SupportedDeviceTable/use-device-models.ts, src/lib/seam/components/SupportedDeviceTable/use-manufacturer.ts, src/lib/seam/components/SupportedDeviceTable/use-manufacturers.ts, tsconfig.json
Note that this enables local storybook development with the new device db, but it will NOT work yet in the live storybook environments yet (will be handled in follow up PR, testing is over here: https://github.com/seamapi/react/pull/524/commits/8c628ab133029329d7d998ffb71f083ae3a84d0e).
=> Add hooks for new devicedb

src/lib/ui/thermostat/TemperatureControlGroup.tsx
I thought it may be helpful to have default props here. This would cover the scenario where a thermostat provider doesn't give us minimum and maximum values (for example, the Nest API does not provide this in API responses, but I believe it may be in the device manual).
=> Add sane defaults for temperature sliders

src/lib/ui/Snackbar/Snackbar.tsx
The `automaticVisibility` prop lets the `Snackbar` component manage its own visibility, without changing existing functionality. This is useful for scenarios where visibility is determined by query results like `isError` or `isSuccess`. This feature solves the problem of needing extra logic to hide the `Snackbar`. Existing implementations are unaffected; this is an opt-in feature.
=> Add automatic visibility behavior to `Snackbar`

src/styles/_supported-device-table.scss
closes #580  
Should now be centered on the final row.
=> fix: SupportedDeviceTable SeeAll button position

src/lib/seam/components/DeviceDetails/DeviceDetails.element.ts, src/lib/seam/components/DeviceDetails/DeviceDetails.tsx, src/lib/seam/components/DeviceDetails/LockDeviceDetails.tsx, src/lib/seam/components/DeviceTable/DeviceTable.element.ts, src/lib/seam/components/DeviceTable/DeviceTable.tsx
This reverts commit fde0c1cfe1e6cb30668c336f28a39960753252a7.
This prop introduces granular customization that is currently out of scope of this project. The recommended work around to hide arbitrary element is to target the CSS classes.
=> Revert "Add `hideAccessCodes` flag to device table (#583)"

src/lib/seam/SeamProvider.tsx
This only exists in v8 contexts and was throwing in Firefox.
It's [not needed](https://stackoverflow.com/a/64063868) when extending the Error class.
=> fix: Error in some contexts when using Error.captureStackTrace()

src/lib/seam/components/DeviceDetails/DeviceDetails.tsx
The "disableCreateAccessCode" and "disableEditAccessCode" property flags are not properly passed through DeviceDetails, so there is no way to disable the edit and create buttons.
=> fix(DeviceDetails): Context menu does not respect `disableCreateAccessCode` and `disableEditAccessCode`

src/lib/seam/components/DeviceDetails/LockDeviceDetails.tsx
Closes #592 • Only show Lock/Unlock button when `capabilities_supported` includes `"lock"`
=> fix: Hide Lock/Unlock button on unsupported devices

src/lib/seam/components/DeviceDetails/ThermostatDeviceDetails.tsx, src/styles/_layout.scss
Fixes an issue where the border of the last `DetailRow` would be visible. This is because the SCSS uses the `:not(:last-of-type)` selector, which operates on element type. To fix it, we needed to make sure that `DetailRow` was the last `div` in any given child `div`. This PR simply wraps those two exceptional elements in an intermediary `div`.
Under "Fan mode" and "Allow manual override"
=> fix: Hide border on `DetailRow:last-of-type`

src/lib/element.tsx, src/lib/seam/components/AccessCodeDetails/AccessCodeDetails.tsx, src/lib/seam/components/AccessCodeTable/AccessCodeTable.tsx, src/lib/seam/components/ClimateSettingScheduleDetails/ClimateSettingScheduleDetails.tsx, src/lib/seam/components/ClimateSettingScheduleTable/ClimateSettingScheduleTable.tsx, src/lib/seam/components/DeviceDetails/DeviceDetails.tsx, src/lib/seam/components/DeviceDetails/LockDeviceDetails.tsx, src/lib/seam/components/DeviceDetails/ThermostatDeviceDetails.tsx, src/lib/seam/components/DeviceTable/DeviceTable.tsx, src/lib/seam/components/common-props.tsx
https://github.com/seamapi/react/assets/87919558/145ffafb-feb6-4611-be39-1d2181a5d912
=> feat: Add `disableClimateSettingSchedules` prop

src/lib/seam/components/DeviceDetails/ThermostatDeviceDetails.tsx
Fixes #601 
https://github.com/seamapi/react/assets/87919558/211d3686-9fb9-4ef5-a7aa-b4533ad1025a
=> fix: Hide default climate settings with `disableClimateSettingSchedules`

src/lib/ui/AccessCodeForm/AccessCodeForm.tsx
=> feat(AccessCode): hide code inputs for offline codes

src/lib/ui/noise-sensor/NoiseThresholdsList.tsx, src/styles/_loading_toast.scss
=> fix: Use `LoadingToast` for `NoiseSensorDeviceDetails`

package-lock.json, package.json
https://github.com/seamapi/react/issues/646 was fixed upstream, we want to use the new version that contains the fix
=> test: Use version of fake-devicedb that supports proxied image urls

package-lock.json, package.json
react-query v5 requires React 18+: https://tanstack.com/query/latest/docs/framework/react/installation
So this is an additional breaking change for Version 3.
=> fix: Only support React 18 in version 3

.storybook/seed-fake.js, src/lib/seam/access-codes/use-access-code.ts, src/lib/seam/access-codes/use-delete-access-code.ts, src/lib/seam/components/AccessCodeDetails/AccessCodeDetails.element.ts, src/lib/seam/components/AccessCodeDetails/AccessCodeDetails.stories.tsx, src/lib/seam/components/AccessCodeDetails/AccessCodeDetails.tsx, src/lib/seam/components/AccessCodeTable/AccessCodeMenu.tsx, src/lib/seam/components/AccessCodeTable/AccessCodeRow.tsx, src/lib/seam/components/AccessCodeTable/AccessCodeTable.tsx, src/lib/ui/Menu/Menu.tsx, src/styles/_seam-table.scss
https://github.com/seamapi/react/issues/449
https://github.com/seamapi/react/issues/651
- Gray out access-code rows when their status is "removing"
- Show a warning in the access-code details view when the access-code's status is "removing"
- Disable edit and delete actions when access-code is in "removing" state
- Optimistically mark access-codes as "removing" when the deletion query is successful
- Show snackbar when access code is deleted
- New props to be able to control onDelete for AccessCodeDetails
- Fix a bug that kept a wrong state for the access-code row menu when closed (reopening it would show the deletion menu instead of the normal menu)
- Fix bug where the AccessCodeDetails was missing a nested edit form
- Circumvent bug with snackbar that causes the wrong message to be …
=> Display warning when access-code is being removed

src/lib/seam/components/AccessCodeDetails/AccessCodeDetails.tsx, src/lib/seam/components/AccessCodeDetails/AccessCodeDevice.tsx, src/lib/seam/components/AccessCodeTable/AccessCodeTable.tsx, src/lib/seam/components/DeviceDetails/LockDeviceDetails.tsx, src/lib/seam/components/DeviceTable/DeviceTable.test.tsx, src/lib/seam/locks/lock-device.ts, src/lib/ui/device/LockStatus.tsx, test/fixtures/api.ts
=> feat: support generic lock devices

.eslintrc.json, src/lib/seam/components/SupportedDeviceTable/FilterCategoryMenu.tsx, src/lib/seam/components/SupportedDeviceTable/ShowAllDevicesButton.tsx, src/lib/ui/Alert/Alert.tsx, src/lib/ui/IconButton.tsx, src/lib/ui/Snackbar/Snackbar.tsx, src/lib/ui/TabSet.tsx, src/lib/ui/TextButton.tsx, src/lib/ui/TextField/TextField.tsx, src/lib/ui/Tooltip/Tooltip.tsx, src/lib/ui/device/EditableDeviceName.tsx, src/lib/ui/layout/AccordionRow.tsx, src/lib/ui/thermostat/ClimateModeMenu.tsx, src/lib/ui/thermostat/FanModeMenu.tsx, src/lib/ui/thermostat/TemperatureControl.tsx, src/lib/ui/thermostat/ThermostatCard.tsx
a type to all buttons in the project is given to prevent unexpected submission.
=> fix: Interacting form submits early

src/lib/seam/SeamProvider.tsx, src/lib/seam/SeamQueryProvider.tsx, src/lib/seam/use-seam-client.ts, src/lib/seam/use-seam-query.ts
- **Pass globalThis.seamQueryClient from SeamProvider**
- **fix: Ensure query key is prefix by session scope**
=> fix: Ensure query key is prefix by session scope

src/lib/seam/components/CreateAccessCodeForm/CreateAccessCodeForm.tsx, src/lib/seam/use-seam-infinite-query.ts, src/lib/seam/use-seam-mutation-without-workspace.ts, src/lib/seam/use-seam-mutation.ts, src/lib/seam/use-seam-query-without-workspace.ts, src/lib/seam/use-seam-query.ts
- **fix: Include action attempt errors in mutation type**
- **fix: Include SeamHttpInvalidInputError in hook type**
=> Extend hook error types

src/lib/seam/use-seam-infinite-query.ts, src/lib/seam/use-seam-query-without-workspace.ts, src/lib/seam/use-seam-query.ts
- **feat: Return queryKey from hooks**
- **Do not allow using page_cursor with useSeamInfiniteQuery**
=> Return queryKey from hooks
